'use strict';
const $ = s => document.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const n = (v, digits=2) => Number(v || 0).toLocaleString('ru-RU',{maximumFractionDigits:digits,minimumFractionDigits:digits});
const rub = v => n(v,0)+' ₽';
const wt = r => Math.PI * r.wall * (r.diameter-r.wall) * 7850 * r.length * (r.qty || 1) / 1e9;
const date = v => new Date(v).toLocaleString('ru-RU',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});
let S, mode = location.pathname === '/system' ? 'system' : 'simple', tab='concepts', selectedMessage='msg-sample', expanded=new Set([530]), detail=null, selected=new Set(), lotDetail=null;
let filters={search:'',lot:'',warehouse:'',availability:'',wall:'',minLength:'',seams:''}, pending=false;
const draftEdits=new Map();
const lot = id => S.lots.find(l=>l.id===id);
const alive = () => S.stock.filter(x=>['available','reserved'].includes(x.status));
const sum = (a, k) => a.reduce((v,x)=>v+Number(x[k]||0),0);
const button = (text, action, cls='', data='') => `<button class="${cls}" data-action="${action}" ${data}>${text}</button>`;
const option = (value,label,current) => `<option value="${esc(value)}" ${String(value)===String(current)?'selected':''}>${esc(label)}</option>`;
const lotOptions = current => S.lots.map(l=>option(l.id,l.name,current)).join('');
const statusTag = status => ({draft:'<span class="tag warn">Проверить</span>',confirmed:'<span class="tag good">Подтверждено</span>',posted:'<span class="tag good">На складе</span>',available:'<span class="tag">Свободно</span>',reserved:'<span class="tag warn">Резерв</span>'}[status]||esc(status));
function toast(text){const t=$('#toast');t.textContent=text;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',4500);}
async function api(action,p){return Demo.act(action,p);}
async function load(){S=await Demo.read();S.messages.filter(m=>m.status!=='draft').forEach(m=>draftEdits.delete(m.id));render();}
const head = (title,subtitle,actions='') => `<div class="pagehead"><div><h1>${title}</h1><p class="muted">${subtitle}</p></div><div class="actions">${actions}</div></div>`;
const empty = text => `<div class="empty">${text}</div>`;
function render(){
 const nav=mode==='simple' ? [['concepts','Варианты решения'],['inbox','Входящие'],['archive','Проверенные ведомости'],['summary','Данные по размерам'],['assistant','Запросить данные'],['journal','История']] : [['concepts','Варианты решения'],['overview','Обзор склада'],['inbox','Приёмка из сообщений'],['lots','Закупочные лоты'],['stock','Склад'],['jobs','Работы'],['sales','Продажи и отгрузки'],['money','Деньги'],['journal','История']];
 if(!nav.some(x=>x[0]===tab))tab=mode==='simple'?'inbox':'overview';
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand">МЕТАЛЛ<span> /</span></div><div class="caption">${mode==='simple'?'Помощник склада':'Рабочий учёт компании'}</div><nav class="nav">${nav.map(([key,label])=>button(label,'nav',key===tab?'active':'',`data-tab="${key}"`)).join('')}</nav><div class="sidebar-bottom"><strong>Демонстрация</strong><br>Изменения только в вашем браузере.<br>Начальные остатки — пример.<br><a href="./api/backup">Скачать данные</a><br><button class="small" data-action="reset-demo">Начать показ заново</button></div></aside><main class="main"><header class="topbar"><div class="switch">${button('Помощник + Excel','mode',mode==='simple'?'active':'','data-mode="simple"')}${button('Склад и бизнес','mode',mode==='system'?'active':'','data-mode="system"')}</div><div class="live">Фото и текст · ${S.messages.length} документов · <span class="unconnected">Telegram не подключён</span></div></header><div class="content">${view()}</div></main></div>`;
}
function view(){return ({concepts,overview,inbox,archive,summary,assistant,lots,stock,jobs,sales,money,journal}[tab])();}
function concepts(){return `${head('Начать с простого. Расширить по необходимости.','Три сценария на одном наборе данных. Выберите, что показать заказчику.')}<div class="concepts"><section class="concept"><div class="step">01 / МИНИМУМ ИЗМЕНЕНИЙ</div><h2>Помощник в Telegram</h2><p>Склад пишет как обычно. Помощник собирает сообщения и документы в понятный архив.</p><div class="flow">Сообщение и фото<br>Проверка размеров<br>Архив, поиск и расшифровка</div><ul><li>Оригинал фото всегда рядом</li><li>Каждая стенка отдельным полем</li><li>Выгрузка по запросу</li></ul><p class="caption">Подходит, когда важно сначала навести порядок во входящей информации.</p>${button('Открыть входящие','concept-open','', 'data-target="inbox"')}</section><section class="concept recommended"><div class="step">02 / РЕКОМЕНДУЕМЫЙ ПЕРВЫЙ ТЕСТ</div><h2>Помощник + Excel</h2><p>После проверки сотрудник получает готовые строки для привычной таблицы.</p><div class="flow">Фото и текст<br>Подтверждённая ведомость<br>Excel с отдельными размерами</div><ul><li>Настоящий файл .xlsx</li><li>Вес считается по формуле</li><li>Исходные таблицы не меняются</li></ul><p class="caption">Прямая запись в рабочую книгу подключается после согласования листа и столбцов.</p>${button('Проверить и выгрузить','concept-open','primary','data-target="inbox"')}</section><section class="concept"><div class="step">03 / УПРАВЛЕНИЕ ОПЕРАЦИЯМИ</div><h2>Склад + помощник</h2><p>Тот же вход из сообщений, а остатки получаются из проведённых операций.</p><div class="flow">Лот и приёмка<br>Склад, резерв и работы<br>Отгрузка, оплаты и результат</div><ul><li>Ассортимент 219–1420 мм</li><li>Резка и сохранение остатков</li><li>Базовая маржа и задолженность</li></ul><p class="caption">Можно вести операции вручную, а Telegram подключить следующим шагом.</p>${button('Открыть рабочий склад','concept-open','','data-target="overview"')}</section></div><div class="card guide"><h2>Что можно проверить прямо сейчас</h2><div class="grid cols2"><div><h3>Простой сценарий</h3><p>Откройте входящие. В третьей строке демо-ведомости уточните число швов. Подтвердите ведомость и скачайте Excel. Фото, текст и отдельные размеры сохранены вместе.</p></div><div><h3>Расширенный сценарий</h3><p>После подтверждения нажмите «Принять на склад». Выберите трубы, создайте резерв, выполните работу или отгрузку. Остатки и деньги обновляются по операции.</p></div></div><div class="notice guide">В MVP работает ручная загрузка сообщений, разбор текстового промера, проверка и учёт. Для новых фото нужна введённая расшифровка: автоматическое распознавание и реальный Telegram пока не подключены.</div></div>`;}
function overview(){const items=alive(),free=items.filter(x=>x.status==='available'),reserved=items.filter(x=>x.status==='reserved');return `${head('Склад сегодня','Все размеры, лоты и операции в одном рабочем месте.',button('Принять металл','nav','primary','data-tab="inbox"'))}<div class="stats"><div class="stat"><label>Металла на складе</label><strong>${n(sum(items,'tons'),3)} т</strong><span class="caption">${items.length} записей · трубы и лом</span></div><div class="stat"><label>Свободно для продажи</label><strong>${n(sum(free,'tons'),3)} т</strong><span class="caption">${free.length} записей</span></div><div class="stat"><label>Зарезервировано</label><strong>${n(sum(reserved,'tons'),3)} т</strong><span class="caption">Физически остаётся на складе</span></div><div class="stat"><label>Входящих на проверку</label><strong>${S.messages.filter(m=>m.status==='draft').length}</strong><span class="caption">Фото и ведомости</span></div></div><div class="split"><div class="card"><div class="reviewhead"><h2>Ассортимент по диаметрам</h2>${button('Весь склад','nav','small','data-tab="stock"')}</div><div class="tablewrap"><table><thead><tr><th>Диаметр</th><th>Точных стенок</th><th class="num">На складе, т</th><th class="num">Свободно, т</th></tr></thead><tbody>${[...new Set(items.filter(x=>x.kind==='pipe').map(x=>x.diameter))].sort((a,b)=>a-b).map(d=>{const a=items.filter(x=>x.diameter===d&&x.kind==='pipe');return `<tr><td>${button(d+' мм','diameter-open','small',`data-d="${d}"`)}</td><td>${new Set(a.map(x=>x.wall)).size}</td><td class="num">${n(sum(a,'tons'),3)}</td><td class="num">${n(sum(a.filter(x=>x.status==='available'),'tons'),3)}</td></tr>`}).join('')}</tbody></table></div></div><div class="grid"><div class="card"><h2>Сейчас стоит проверить</h2>${S.messages.filter(m=>m.status==='draft').map(m=>`<div class="row"><div><strong>${esc(m.title)}</strong><p class="caption">${m.rows.length} строк · ${m.rows.filter(r=>r.seams===null).length} неуточнённых значений</p></div>${button('Открыть','open-message','small',`data-id="${m.id}"`)}</div>`).join('')||empty('Входящие проверены')}</div><div class="card"><h2>Последние операции</h2>${S.events.slice(0,5).map(x=>`<div class="row"><div>${esc(x.title)}<p class="caption">${date(x.at)}</p></div></div>`).join('')}</div></div></div>`;}
function inbox(){let m=S.messages.find(x=>x.id===selectedMessage)||S.messages[0];if(m)selectedMessage=m.id;return `${head(mode==='simple'?'Входящие со склада':'Приёмка из сообщений','Сначала проверяем исходный документ. Затем передаём данные в учёт.',button('Добавить сообщение или фото','new-message','primary'))}<div class="notice">${mode==='simple'?'В этой версии подтверждение сохраняет ведомость. Складской остаток не меняется. Excel можно скачать сразу после проверки.':'Подтверждение проверяет ведомость. Отдельная кнопка «Принять на склад» создаёт приход и обновляет остатки.'}</div><div class="inbox"><div class="messages">${S.messages.map(x=>`<button class="message ${x.id===selectedMessage?'active':''}" data-action="message-select" data-id="${x.id}">${statusTag(x.status)}<h3>${esc(x.title)}</h3><span class="caption">${esc(lot(x.lot_id)?.name)}<br>${x.rows.length} строк · ${date(x.at)}</span></button>`).join('')}</div><div class="card">${m?review(m):empty('Загрузите первое сообщение')}</div></div>`;}
function review(m){if(m.status==='draft'&&draftEdits.has(m.id))m={...m,...draftEdits.get(m.id)};const readonly=m.status!=='draft';return `<div class="reviewhead"><div><h2>${esc(m.title)}</h2><span class="caption">${esc(m.source)} · ${esc(m.sender)}</span></div>${statusTag(m.status)}</div><div class="source">${m.photo?`<img src="${esc(Demo.photo(m.photo))}" alt="Исходная фотография ведомости" data-action="photo" data-id="${m.id}">`:'<div class="empty compact">Текстовое сообщение</div>'}<div><pre>${esc(m.text||'Фото сохранено. Добавьте строки по исходнику вручную.')}</pre><div class="doclinks">${m.photo?`<a href="${esc(Demo.photo(m.photo))}" target="_blank" rel="noopener">Открыть фото</a>`:''}<a href="./api/transcript/${m.id}">Текст .txt</a><a href="./api/structured/${m.id}">Данные .json</a></div></div></div>${m.rows.some(r=>r.seams===null)?'<div class="notice warn">Число поперечных швов не уточнено. П2 означает два шва, количество труб указывается отдельно. Заполните жёлтые строки перед подтверждением.</div>':''}${m.unmatched?.length?`<div class="notice warn">${m.unmatched.length} строк текста не разобрано. Проверьте, что все позиции добавлены: ${esc(m.unmatched.join(' · '))}</div>`:''}<div class="formrow"><label class="field">Закупочный лот<select id="review-lot" ${readonly?'disabled':''}>${lotOptions(m.lot_id)}</select></label><label class="field">Сектор хранения<input id="review-sector" value="${esc(m.sector)}" ${readonly?'disabled':''}></label></div><div class="tablewrap"><table class="edit-table" id="review-table"><thead><tr><th>№</th><th>Диаметр, мм</th><th>Стенка, мм</th><th>Длина, м</th><th>Труб, шт.</th><th>Поперечные швы</th><th class="num">Вес, т</th>${readonly?'':'<th></th>'}</tr></thead><tbody>${m.rows.map((r,i)=>reviewRow(r,i,readonly)).join('')}</tbody></table></div>${readonly?'':button('+ Добавить строку','add-row','small')}<div class="totals"><span>Позиций: <strong id="rows-count">${m.rows.length}</strong></span><span>Труб: <strong id="rows-qty">${sum(m.rows,'qty')}</strong></span><span>Расчётный вес: <strong id="rows-tons">${n(m.rows.reduce((v,r)=>v+wt(r),0),3)} т</strong></span></div><div class="reviewfoot"><span class="caption">${readonly?'Подтверждено '+date(m.reviewed_at):'Вес по геометрии, плотность 7850 кг/м³. Данные фото не считаются весами.'}</span><div class="actions">${!readonly?button('Подтвердить ведомость','confirm','primary',`data-id="${m.id}"`):'<a class="tag" href="./api/export.xlsx">Скачать Excel</a>'}${mode==='system'&&m.status==='confirmed'?button('Принять на склад','post','primary',`data-id="${m.id}"`):''}</div></div>${m.status==='posted'?`<p class="caption success">Приход проведён ${date(m.posted_at)}. Повторно принять эту ведомость нельзя.</p>`:''}`;}
function reviewRow(r,i,ro=false){return `<tr class="${r.seams===null?'uncertain':''}"><td>${i+1}</td>${['diameter','wall','length','qty','seams'].map(k=>`<td>${ro?esc(r[k]):`<input type="number" data-field="${k}" value="${r[k]??''}" step="${['qty','seams'].includes(k)?'1':'.01'}" min="${k==='seams'?'0':'.01'}" aria-label="${k} строка ${i+1}" ${r[k]===null?'placeholder="Уточнить"':''}>`}</td>`).join('')}<td class="num row-weight">${n(wt(r),3)}</td>${ro?'':`<td>${button('×','remove-row','small danger',`aria-label="Удалить строку ${i+1}"`)}</td>`}</tr>`;}
function readRows(){return [...document.querySelectorAll('#review-table tbody tr')].map(tr=>Object.fromEntries([...tr.querySelectorAll('[data-field]')].map(el=>[el.dataset.field,el.value===''?null:Number(el.value)])));}
function updateTotals(){const rows=readRows();$('#rows-count').textContent=rows.length;$('#rows-qty').textContent=sum(rows,'qty');$('#rows-tons').textContent=n(rows.reduce((v,r)=>v+wt(r),0),3)+' т';document.querySelectorAll('#review-table tbody tr').forEach((tr,i)=>{tr.querySelector('.row-weight').textContent=n(wt(rows[i]),3);tr.cells[0].textContent=i+1;});draftEdits.set(selectedMessage,{rows,lot_id:$('#review-lot').value,sector:$('#review-sector').value});}
function archive(){return `${head('Проверенные ведомости','Фото, расшифровка и подтверждённые размеры остаются связаны.','<a href="./api/export.xlsx"><button class="primary">Скачать Excel</button></a>')}<div class="card tablewrap"><table><thead><tr><th>Документ</th><th>Лот</th><th>Строк</th><th class="num">Труб</th><th class="num">Вес, т</th><th>Статус</th><th></th></tr></thead><tbody>${S.messages.filter(m=>m.status!=='draft').map(m=>`<tr><td><strong>${esc(m.title)}</strong><p class="caption">${date(m.reviewed_at)}</p></td><td>${esc(lot(m.lot_id)?.name)}</td><td>${m.rows.length}</td><td class="num">${sum(m.rows,'qty')}</td><td class="num">${n(m.rows.reduce((v,r)=>v+wt(r),0),3)}</td><td>${statusTag(m.status)}</td><td>${button('Открыть','open-message','small',`data-id="${m.id}"`)}</td></tr>`).join('')}</tbody></table>${S.messages.every(m=>m.status==='draft')?empty('Подтвердите первую ведомость во входящих'):''}</div><div class="card guide"><h2>Что будет в Excel</h2><p>Отдельный лист проверенных строк: документ, лот, склад, диаметр, точная стенка, длина, количество труб, число швов, ссылка на исходный файл и формула расчётного веса.</p><p class="caption">Это новая выгрузка. Рабочие книги заказчика не открываются и не перезаписываются. Прямую запись согласуем отдельно по листу и столбцам.</p></div>`;}
function summary(){let rows=[];S.messages.filter(m=>m.status!=='draft').forEach(m=>m.rows.forEach(r=>rows.push({...r,warehouse:m.warehouse,lot_id:m.lot_id})));const groups={};rows.forEach(r=>{const k=r.diameter+'|'+r.wall;groups[k]??={d:r.diameter,w:r.wall,qty:0,meters:0,tons:0};groups[k].qty+=r.qty;groups[k].meters+=r.length*r.qty;groups[k].tons+=wt(r)});return `${head('Данные по размерам','Сводка только по проверенным входящим ведомостям.')}<div class="notice warn">Это количество по документам поступления, а не текущий остаток. Для остатка нужны также подтверждённые отгрузки, работы и списания — они есть в расширенной версии.</div><div class="card tablewrap"><table><thead><tr><th>Диаметр × стенка</th><th class="num">Труб, шт.</th><th class="num">Длина, м</th><th class="num">Вес, т</th></tr></thead><tbody>${Object.values(groups).sort((a,b)=>a.d-b.d||a.w-b.w).map(g=>`<tr><td><strong>${g.d} × ${g.w} мм</strong></td><td class="num">${g.qty}</td><td class="num">${n(g.meters)}</td><td class="num">${n(g.tons,3)}</td></tr>`).join('')}</tbody></table>${rows.length?'':empty('Пока нет подтверждённых строк')}</div>`;}
function assistant(){return `${head('Запросить данные','Помощник выдаёт информацию из сохранённых документов.')}<div class="assistant"><div class="card"><h2>Что найти?</h2><label class="field">Источник данных<select id="query-source">${option('docs','Проверенные ведомости','docs')}${option('stock','Текущий склад расширенной версии','docs')}</select></label><div class="formrow"><label class="field">Диаметр, мм<input id="query-d" type="number" placeholder="Например, 720"></label><label class="field">Точная стенка, мм<input id="query-w" type="number" step=".1" placeholder="Например, 7.5"></label></div>${button('Найти размеры','query','primary')}<div id="answer"></div></div><div class="card"><h2>Как это будет в Telegram</h2><p>«Покажи 720 со стенкой 7,5»</p><p>«Пришли ведомость по лоту Ярославль»</p><p>«Открой фото по этому поступлению»</p><div class="flow">Ответ содержит найденные строки и исходники. Если данных нет, помощник сообщает об этом и не придумывает наличие.</div><p class="caption">Здесь работает поиск по заданным полям. Свободный диалог с агентом подключается через существующий MetalAgent.</p></div></div>`;}
function filterStock(){return alive().filter(x=>(!filters.lot||x.lot_id===filters.lot)&&(!filters.warehouse||x.warehouse===filters.warehouse)&&(!filters.availability||x.status===filters.availability)&&(!filters.wall||x.wall===Number(filters.wall))&&(!filters.minLength||x.length>=Number(filters.minLength))&&(filters.seams===''||x.seams===Number(filters.seams))&&(!filters.search||`${x.diameter} ${x.wall} ${lot(x.lot_id)?.name} ${x.reserve} ${x.sector}`.toLowerCase().includes(filters.search.toLowerCase())));}
function stock(){const items=filterStock(),sel=alive().filter(x=>selected.has(x.id));if(detail){const a=items.filter(x=>x.diameter===detail.d&&x.wall===detail.w&&x.kind===detail.kind);return `${stockHead()}${selectionBar(sel)}${filterBar()}<div class="breadcrumb">${button('Все диаметры','back-stock','small')} / ${detail.kind==='scrap'?'Лом':detail.d+' × '+detail.w+' мм'}</div><div class="card"><div class="reviewhead"><h2>${detail.kind==='scrap'?'Возвратный лом':'Трубы '+detail.d+' × '+detail.w+' мм'}</h2><span class="caption">${a.length} записей · ${n(sum(a,'tons'),3)} т</span></div><div class="notice">Номер записи служит для учёта. Физическую маркировку труб и порядок отбора согласуем со складом.</div><div class="tablewrap"><table><thead><tr><th><input type="checkbox" data-select-all="1" aria-label="Выбрать все строки"></th><th>Запись</th><th>Размер, мм</th><th class="num">Длина, м</th><th>Швы</th><th class="num">Вес, т</th><th>Лот / место</th><th>Доступность</th><th>Работы</th><th>Источник</th></tr></thead><tbody>${a.map(x=>pipeRow(x)).join('')}</tbody></table></div>${a.length?'':empty('Нет подходящих позиций')}</div>`;}
 const diameters=[...new Set(items.filter(x=>x.kind==='pipe').map(x=>x.diameter))].sort((a,b)=>a-b);
 return `${stockHead()}${selectionBar(sel)}${filterBar()}<div class="card tablewrap"><table><thead><tr><th>Диаметр / точная стенка</th><th class="num">Записей</th><th class="num">Метры</th><th class="num">На складе, т</th><th class="num">Свободно, т</th><th class="num">Резерв, т</th><th></th></tr></thead><tbody>${diameters.map(d=>{const a=items.filter(x=>x.diameter===d&&x.kind==='pipe');return `<tr class="diameter" data-action="expand" data-d="${d}"><td>${expanded.has(d)?'▾':'▸'} ${d} мм <span class="quiet muted"> / ${new Set(a.map(x=>x.wall)).size} стенок</span></td><td class="num">${a.length}</td><td class="num">${n(sum(a,'length'))}</td><td class="num">${n(sum(a,'tons'),3)}</td><td class="num">${n(sum(a.filter(x=>x.status==='available'),'tons'),3)}</td><td class="num">${n(sum(a.filter(x=>x.status==='reserved'),'tons'),3)}</td><td></td></tr>${expanded.has(d)?[...new Set(a.map(x=>x.wall))].sort((a,b)=>a-b).map(w=>{const g=a.filter(x=>x.wall===w);return `<tr class="wall"><td>${d} × ${w} мм</td><td class="num">${g.length}</td><td class="num">${n(sum(g,'length'))}</td><td class="num">${n(sum(g,'tons'),3)}</td><td class="num">${n(sum(g.filter(x=>x.status==='available'),'tons'),3)}</td><td class="num">${n(sum(g.filter(x=>x.status==='reserved'),'tons'),3)}</td><td>${button('Открыть трубы','wall-open','small',`data-d="${d}" data-w="${w}" data-kind="pipe"`)}</td></tr>`}).join(''):''}`}).join('')}${items.some(x=>x.kind==='scrap')?`<tr><td>Возвратный лом</td><td class="num">${items.filter(x=>x.kind==='scrap').length}</td><td></td><td class="num">${n(sum(items.filter(x=>x.kind==='scrap'),'tons'),3)}</td><td colspan="3">${[...new Set(items.filter(x=>x.kind==='scrap').map(x=>x.diameter+'|'+x.wall))].map(k=>{const[d,w]=k.split('|');return button(d+' × '+w,'wall-open','small',`data-d="${d}" data-w="${w}" data-kind="scrap"`)}).join(' ')}</td></tr>`:''}</tbody></table>${items.length?'':empty('Нет подходящих остатков')}</div>`;}
function stockHead(){return head('Склад металла','Диаметр → точная стенка → отдельные записи и исходные документы.',button('Ручной приход','new-message','primary'));}
function selectionBar(a){return a.length?`<div class="selection"><div><strong>Выбрано ${a.length} записей · ${n(sum(a,'tons'),3)} т</strong><div class="caption">Резерв не изменяет длину или физический остаток</div></div><div class="actions">${button('Операция с выбранными','stock-dialog')}${button('Снять выбор','clear-selection','small')}</div></div>`:'';}
function filterBar(){return `<div class="filters"><input class="searchwide" data-filter="search" placeholder="Диаметр, лот, покупатель…" value="${esc(filters.search)}"><select data-filter="lot">${option('','Все лоты',filters.lot)}${lotOptions(filters.lot)}</select><select data-filter="warehouse">${option('','Все склады',filters.warehouse)}${[...new Set(alive().map(x=>x.warehouse))].map(w=>option(w,w,filters.warehouse)).join('')}</select><select data-filter="availability">${option('','Свободно + резерв',filters.availability)}${option('available','Только свободно',filters.availability)}${option('reserved','Только резерв',filters.availability)}</select><input type="number" data-filter="wall" step=".1" placeholder="Стенка, мм" value="${filters.wall}" aria-label="Стенка" class="narrow"><input type="number" data-filter="minLength" step=".1" placeholder="Длина от, м" value="${filters.minLength}" aria-label="Минимальная длина" class="narrow"><select data-filter="seams">${option('','Все швы',filters.seams)}${option('0','Без швов',filters.seams)}${option('1','Один шов',filters.seams)}${option('2','Два шва',filters.seams)}</select>${button('Сбросить','reset-filters','small')}</div>`;}
function pipeRow(x){const index=S.stock.findIndex(a=>a.id===x.id)+1;return `<tr><td><input type="checkbox" data-select="${x.id}" ${selected.has(x.id)?'checked':''} aria-label="Выбрать запись ${index}"></td><td>№ ${index}${x.parent?'<p class="caption">После обработки</p>':''}</td><td>${x.kind==='scrap'?'Лом из ':''}${x.diameter} × ${x.wall}</td><td class="num">${n(x.length)}</td><td>${x.seams}</td><td class="num">${n(x.tons,3)}</td><td>${esc(lot(x.lot_id)?.name)}<p class="caption">${esc(x.warehouse)} · ${esc(x.sector)}</p></td><td>${statusTag(x.status)}${x.reserve?`<p class="caption">${esc(x.reserve)}</p>`:''}</td><td>${esc(x.work)}</td><td>${x.origin.startsWith('msg')?button('Ведомость','open-message','small',`data-id="${x.origin}"`):'<span class="caption">Демо-остаток</span>'}</td></tr>`;}
function lots(){if(lotDetail){const l=lot(lotDetail),a=alive().filter(x=>x.lot_id===l.id),all=S.stock.filter(x=>x.lot_id===l.id),docs=S.messages.filter(x=>x.lot_id===l.id);return `${head(esc(l.name),'Поставщик: '+esc(l.supplier)+' · Склад: '+esc(l.warehouse),button('Все лоты','back-lots'))}<div class="stats"><div class="stat"><label>На складе</label><strong>${n(sum(a,'tons'),3)} т</strong><span class="caption">${a.length} записей</span></div><div class="stat"><label>Стоимость остатка</label><strong>${rub(sum(a,'cost'))}</strong><span class="caption">Закупка + доставка + работы</span></div><div class="stat"><label>Закупка за тонну</label><strong>${rub(l.rate)}</strong><span class="caption">Доставка ${rub(l.landing)} / т</span></div><div class="stat"><label>Связанных ведомостей</label><strong>${docs.length}</strong><span class="caption">Можно принимать несколькими машинами</span></div></div><div class="grid cols2"><div class="card"><h2>Поступления по лоту</h2>${docs.map(m=>`<div class="row"><div><strong>${esc(m.title)}</strong><p>${statusTag(m.status)}</p></div>${button('Открыть','open-message','small',`data-id="${m.id}"`)}</div>`).join('')||empty('Пока нет ведомостей')}${button('Добавить поступление','new-message','primary',`data-lot="${l.id}"`)}</div><div class="card"><h2>Правило стоимости</h2><p>Каждая принятая труба получает стоимость: расчётный вес × (цена закупки за тонну + доставка за тонну).</p><p>Работы добавляются к стоимости выбранных труб. При отгрузке в результат попадает стоимость только отгруженных позиций.</p><p class="caption">Цена лота целиком, фактические весы и распределение общих расходов — отдельное расширение. Здесь выбран один прозрачный способ для MVP.</p></div></div>`;}
 return `${head('Закупочные лоты','Создание лота ещё не создаёт остаток. Металл появляется после приёмки.',button('+ Создать лот','new-lot','primary'))}<div class="card tablewrap"><table><thead><tr><th>Лот</th><th>Поставщик</th><th>Склад</th><th class="num">Закупка, ₽/т</th><th class="num">На складе, т</th><th></th></tr></thead><tbody>${S.lots.map(l=>`<tr><td><strong>${esc(l.name)}</strong><p class="caption">${date(l.at)}</p></td><td>${esc(l.supplier)}</td><td>${esc(l.warehouse)}</td><td class="num">${rub(l.rate)}</td><td class="num">${n(sum(alive().filter(x=>x.lot_id===l.id),'tons'),3)}</td><td>${button('Открыть','lot-open','small',`data-id="${l.id}"`)}</td></tr>`).join('')}</tbody></table></div>`;}
function jobs(){return `${head('Работы по металлу','Операция применяется к выбранным трубам; результат меняет их стоимость и состояние.',button('Выбрать трубы','nav','primary','data-tab="stock"'))}<div class="card"><h2>Выполненные работы</h2><div class="tablewrap"><table><thead><tr><th>Работа</th><th>Дата</th><th>Исходных записей</th><th>Результат</th><th class="num">Стоимость</th></tr></thead><tbody>${S.jobs.map(j=>`<tr><td><strong>${esc(j.title)}</strong></td><td>${date(j.at)}</td><td>${j.ids.length}</td><td>${j.children?`${j.children.length} отрезка · потеря ${n(j.loss,3)} м`:'Состояние обновлено'}</td><td class="num">${rub(j.cost)}</td></tr>`).join('')}</tbody></table></div>${S.jobs.length?'':empty('Выберите трубы на складе и выполните очистку, фаску или резку')}</div><div class="grid cols2 guide"><div class="card"><h3>Очистка, фаска и другие работы</h3><p>Фиксируем факт выполнения и сумму затрат. Стоимость работы распределяется на выбранные трубы по их расчётному весу.</p></div><div class="card"><h3>Резка</h3><p>Исходная труба закрывается, появляются отрезки с тем же лотом. Сумма длин отрезков и потери должна совпасть с исходной длиной. Число швов каждого отрезка вводится по факту.</p></div></div>`;}
function sales(){return `${head('Продажи и отгрузки','Направление продажи выбирает сотрудник. Швы и стенка не определяют его автоматически.',button('Подобрать трубы','nav','primary','data-tab="stock"'))}<div class="card tablewrap"><table><thead><tr><th>Покупатель / дата</th><th>Направление</th><th class="num">Вес, т</th><th class="num">Выручка</th><th class="num">Стоимость металла</th><th class="num">Маржа</th><th class="num">Долг</th><th></th></tr></thead><tbody>${S.sales.map(x=>{const paid=sum(S.payments.filter(p=>p.sale_id===x.id),'amount');return `<tr><td><strong>${esc(x.customer)}</strong><p class="caption">${date(x.at)}</p></td><td>${esc(x.direction)}</td><td class="num">${n(x.tons,3)}</td><td class="num">${rub(x.revenue)}</td><td class="num">${rub(x.cost)}</td><td class="num ${x.margin<0?'risk':'success'}">${rub(x.margin)}</td><td class="num">${rub(x.revenue-paid)}</td><td>${x.revenue-paid>.01?button('Записать оплату','payment','small',`data-id="${x.id}"`):'<span class="tag good">Оплачено</span>'}</td></tr>`}).join('')}</tbody></table>${S.sales.length?'':empty('Отгрузите выбранные трубы на складе, чтобы увидеть продажу и долг')}</div><div class="notice guide">Деловой 1 — продажа перекупам. Деловой 2 — конечным покупателям. Лом — продажа по цене металлолома. Продажа лома и безвозвратное списание учитываются разными операциями.</div>`;}
function money(){const revenue=sum(S.sales,'revenue'),received=sum(S.payments,'amount'),margin=sum(S.sales,'margin'),inventory=sum(alive(),'cost'),loss=sum(S.events.filter(e=>e.kind==='writeoff').map(e=>e.details),'loss_cost')+sum(S.jobs,'loss_cost');return `${head('Базовые деньги','Выручка, стоимость проданного металла, оплаты и долг — раздельно.')}<div class="stats"><div class="stat"><label>Выручка по отгрузкам</label><strong>${rub(revenue)}</strong><span class="caption">Начислена, даже если не оплачена</span></div><div class="stat"><label>Получено от покупателей</label><strong>${rub(received)}</strong><span class="caption">Фактически введённые оплаты</span></div><div class="stat"><label>Долг покупателей</label><strong>${rub(revenue-received)}</strong><span class="caption">Выручка минус оплаты</span></div><div class="stat"><label>Маржа проданного металла</label><strong>${rub(margin)}</strong><span class="caption">До общих расходов и налогов</span></div></div><div class="grid cols2"><div class="card"><h2>Из чего складывается результат</h2><div class="row"><span>Начисленная выручка</span><strong>${rub(revenue)}</strong></div><div class="row"><span>Стоимость отгруженных позиций</span><strong>${rub(sum(S.sales,'cost'))}</strong></div><div class="row"><span>Маржа по продажам</span><strong>${rub(margin)}</strong></div><div class="row"><span>Потери от списания и резки</span><strong>${rub(loss)}</strong></div><div class="row"><span>Результат после этих потерь</span><strong>${rub(margin-loss)}</strong></div><p class="caption">Получение оплаты уменьшает долг и не создаёт повторную выручку или маржу.</p></div><div class="card"><h2>Деньги в металле</h2><div class="row"><span>Стоимость текущего остатка</span><strong>${rub(inventory)}</strong></div><p>В остатке сохраняется стоимость непроданного металла. Она попадёт в расходы продажи при отгрузке конкретных позиций.</p><div class="notice guide">Это управленческая модель MVP. Здесь нет НДС, налогов, общих расходов, выплат поставщикам и банковской сверки. Маржа не равна чистой прибыли или остатку денег на счёте.</div>${button('Посмотреть продажи и оплаты','nav','','data-tab="sales"')}</div></div>`;}
function journal(){return `${head('История операций','Каждое подтверждение и движение оставляет запись.','<a href="./api/backup"><button>Скачать данные JSON</button></a>')}<div class="card tablewrap"><table><thead><tr><th>Дата</th><th>Действие</th><th>Связанные данные</th></tr></thead><tbody>${S.events.map(x=>`<tr><td>${date(x.at)}</td><td>${esc(x.title)}</td><td>${x.details.message_id?button('Документ','open-message','small',`data-id="${x.details.message_id}"`):`<span class="caption">${x.details.ids?x.details.ids.length+' записей':x.details.lot_id?esc(lot(x.details.lot_id)?.name):'Сохранено в журнале'}</span>`}</td></tr>`).join('')}</tbody></table></div>`;}
function modal(title,body,form='',submit='Сохранить'){const el=$('#modal');el.innerHTML=`<div class="modalhead"><h2>${title}</h2>${button('×','close-modal','small','aria-label="Закрыть"')}</div>${form?`<form id="${form}">${body}<div id="form-error"></div><div class="modalfoot">${button('Отмена','close-modal')}<button class="primary" type="submit">${submit}</button></div></form>`:body}`;el.showModal();}
function newMessage(defaultLot){modal('Добавить сообщение или фото',`<div class="notice">Вставьте текст промера или приложите фото. Новые фото сохраняются; размеры по ним в MVP вводятся вручную.</div><label class="field">Название<input name="title" value="Ведомость со склада" required maxlength="250"></label><label class="field">Лот<select name="lot_id">${lotOptions(defaultLot||S.lots[0].id)}</select></label><label class="field">Сообщение / расшифровка<textarea name="text" rows="7" placeholder="720&#10;1) 10,80 x 7,5 П2&#10;2) 9,35 x 8 П1"></textarea></label><p class="caption">Полный формат: 530x7.5 длина 10.8 шт 2 П0. П2 — два шва. Если швы не указаны, их нужно уточнить.</p><label class="field">Фото ведомости<input name="photo" type="file" accept="image/png,image/jpeg,image/webp"></label>`,'message-form','Сохранить и проверить');}
function newLot(){modal('Новый закупочный лот',`<label class="field">Название лота<input name="name" placeholder="Ярославль · тендер 25" required maxlength="250"></label><label class="field">Поставщик<input name="supplier" required maxlength="250"></label><label class="field">Склад<input name="warehouse" value="Ярославль" required maxlength="250"></label><div class="formrow"><label class="field">Закупка, ₽ за тонну<input name="rate" type="number" min="0" step=".01" value="29000" required></label><label class="field">Доставка, ₽ за тонну<input name="landing" type="number" min="0" step=".01" value="2000" required></label></div><div class="notice">Стоимость новых труб считается по расчётному весу. Лот может содержать разные диаметры и поступать несколькими машинами.</div><label class="field">Примечание<textarea name="note" rows="2"></textarea></label>`,'lot-form','Создать лот');}
let operation='reserve';
function stockDialog(op='reserve'){operation=op;const a=alive().filter(x=>selected.has(x.id));if(!a.length)return toast('Выберите трубы');const operations=[['reserve','Зарезервировать'],['release','Снять резерв'],['move','Переместить'],['work','Выполнить работу'],['cut','Разрезать трубу'],['ship','Отгрузить / продать'],['writeoff','Списать / перевести в лом']];let fields='';
 if(op==='reserve')fields='<label class="field">Покупатель / заказ<input name="customer" required maxlength="250" placeholder="Строймонтаж · заказ 18"></label><div class="notice">Резерв блокирует отгрузку другому покупателю. Длины и физический остаток не меняются.</div>';
 if(op==='release')fields='<div class="notice">Выбранные зарезервированные позиции снова станут свободными.</div>';
 if(op==='move')fields='<label class="field">Склад назначения<input name="warehouse" required value="Ярославль"></label><label class="field">Сектор<input name="sector" required value="Б-2"></label>';
 if(op==='work')fields='<label class="field">Работа<select name="title"><option>Очистка</option><option>Фаска</option><option>Правка</option></select></label><label class="field">Затраты на выбранные трубы, ₽<input name="cost" type="number" min="0" step=".01" value="3000" required></label><div class="notice">Фиксируем выполненную работу. Затраты распределяются на выбранные позиции по расчётному весу.</div>';
 if(op==='cut'){const x=a[0];fields=`<div class="notice ${a.length!==1?'warn':''}">Для резки нужна одна свободная труба. Выбрано: ${a.length}. Исходная длина первой: ${n(x.length)} м.</div><label class="field">Длины отрезков через точку с запятой<input name="lengths" value="6; ${n(x.length-6-.01).replace(/\s/g,'')}" required></label><label class="field">Фактические швы каждого отрезка через точку с запятой<input name="seams" value="0; 0" required></label><div class="formrow"><label class="field">Потеря на рез, м<input name="loss" type="number" step=".001" min="0" value="0.01" required></label><label class="field">Стоимость резки, ₽<input name="cost" type="number" step=".01" min="0" value="500" required></label></div><p class="caption">Баланс: отрезки + потеря = исходная длина. Номер исходной записи сохраняется в происхождении каждого отрезка.</p>`;}
 if(op==='ship')fields=`<label class="field">Покупатель<input name="customer" value="${esc(a.find(x=>x.reserve)?.reserve||'')}" required maxlength="250" placeholder="Название компании"></label><label class="field">Направление<select name="direction"><option>Деловой 1</option><option>Деловой 2</option><option>Лом</option></select></label><div class="formrow"><label class="field">Цена продажи, ₽ за тонну<input name="rate" type="number" min=".01" step=".01" value="45000" required></label><label class="field">Получено сейчас, ₽<input name="paid" type="number" min="0" step=".01" value="0" required></label></div><div class="notice">Выбрано ${n(sum(a,'tons'),3)} т. Стоимость металла: ${rub(sum(a,'cost'))}. Оплата и выручка учитываются отдельно.</div><div id="sale-preview" class="totals"></div>`;
 if(op==='writeoff')fields='<label class="field">Причина<input name="reason" required maxlength="250" placeholder="Повреждение при разгрузке"></label><label class="field">Что остаётся<select name="method"><option value="scrap">Весь металл переводим в возвратный лом</option><option value="loss">Безвозвратная потеря</option></select></label><div class="notice warn">Возвратный лом остаётся на складе с той же стоимостью. Безвозвратная потеря списывает стоимость. Продажа лома проводится отдельно.</div>';
 modal('Операция с выбранным металлом',`<p class="caption">${a.length} записей · ${n(sum(a,'tons'),3)} т</p><label class="field">Операция<select id="operation-select">${operations.map(([v,l])=>option(v,l,op)).join('')}</select></label>${fields}`,'stock-form','Провести операцию');salePreview();}
function salePreview(){const el=$('#sale-preview');if(!el)return;const a=alive().filter(x=>selected.has(x.id)),rate=Number($('#stock-form [name=rate]').value),revenue=sum(a,'tons')*rate;el.innerHTML=`<span>Выручка: <strong>${rub(revenue)}</strong></span><span>Маржа: <strong>${rub(revenue-sum(a,'cost'))}</strong></span>`;}
function modalError(text){const el=$('#form-error');if(el)el.innerHTML=`<div class="error">${esc(text)}</div>`;else toast(text);}
async function run(action,p,success){if(pending)return;pending=true;try{const result=await api(action,p);await load();toast(result.duplicate?'Повтор уже сохранён. Новая запись не создана.':success);return result;}catch(e){modalError(e.message);throw e;}finally{pending=false;}}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();const a=el.dataset.action;
 try{
 if(a==='nav'){tab=el.dataset.tab;render();}
 if(a==='mode'){mode=el.dataset.mode;tab=mode==='simple'?'inbox':'overview';selected.clear();render();}
 if(a==='concept-open'){tab=el.dataset.target;mode=tab==='overview'?'system':'simple';render();}
 if(a==='message-select'){selectedMessage=el.dataset.id;render();}
 if(a==='open-message'){selectedMessage=el.dataset.id;tab='inbox';render();}
 if(a==='new-message')newMessage(el.dataset.lot);
 if(a==='new-lot')newLot();
 if(a==='close-modal')$('#modal').close();
 if(a==='photo'){const m=S.messages.find(x=>x.id===el.dataset.id);modal('Исходная фотография',`<img class="photo-full" src="${esc(Demo.photo(m.photo))}" alt="Оригинал ведомости">`);}
 if(a==='add-row'){$('#review-table tbody').insertAdjacentHTML('beforeend',reviewRow({diameter:720,wall:7.5,length:10,qty:1,seams:null},readRows().length));updateTotals();}
 if(a==='remove-row'){el.closest('tr').remove();updateTotals();}
 if(a==='confirm'){const rows=readRows();if(rows.some(r=>r.seams===null))return toast('Уточните количество швов во всех строках');await run('confirm',{id:el.dataset.id,rows,lot_id:$('#review-lot').value,sector:$('#review-sector').value},'Ведомость проверена и сохранена. Можно скачать Excel.');}
 if(a==='post')await run('post',{id:el.dataset.id},'Металл принят на склад. Остатки обновлены.');
 if(a==='expand'){const d=Number(el.dataset.d);expanded.has(d)?expanded.delete(d):expanded.add(d);render();}
 if(a==='diameter-open'){tab='stock';detail=null;filters={...filters,search:el.dataset.d};expanded.add(Number(el.dataset.d));render();}
 if(a==='wall-open'){detail={d:Number(el.dataset.d),w:Number(el.dataset.w),kind:el.dataset.kind};render();}
 if(a==='back-stock'){detail=null;render();}
 if(a==='reset-filters'){filters={search:'',lot:'',warehouse:'',availability:'',wall:'',minLength:'',seams:''};render();}
 if(a==='clear-selection'){selected.clear();render();}
 if(a==='stock-dialog')stockDialog();
 if(a==='lot-open'){lotDetail=el.dataset.id;render();}
 if(a==='back-lots'){lotDetail=null;render();}
 if(a==='payment'){const x=S.sales.find(x=>x.id===el.dataset.id),debt=x.revenue-sum(S.payments.filter(p=>p.sale_id===x.id),'amount');modal('Оплата от '+esc(x.customer),`<input name="id" type="hidden" value="${x.id}"><p>Осталось оплатить: <strong>${rub(debt)}</strong></p><label class="field">Сумма оплаты, ₽<input name="amount" type="number" min=".01" max="${debt.toFixed(2)}" step=".01" required value="${debt.toFixed(2)}"></label>`,'payment-form','Записать оплату');}
 if(a==='query'){const d=$('#query-d').value,w=$('#query-w').value,source=$('#query-source').value;let rows=[];if(source==='stock')rows=alive();else S.messages.filter(m=>m.status!=='draft').forEach(m=>m.rows.forEach(r=>rows.push({...r,tons:wt(r),document:m.title})));rows=rows.filter(r=>(!d||r.diameter===Number(d))&&(!w||r.wall===Number(w)));$('#answer').innerHTML=`<div class="answer"><strong>${source==='stock'?'Текущий склад':'По проверенным ведомостям'}</strong><br>${rows.length?`${sum(rows,'qty')} труб / записей · ${n(sum(rows,'tons'),3)} т<br>`+rows.slice(0,20).map(r=>`${r.diameter} × ${r.wall} мм · ${n(r.length)} м · ${r.qty||1} шт. · ${r.seams} швов`).join('<br>')+(rows.length>20?'<br>Показаны первые 20 строк. Полный список — в Excel.':''):'Подходящих данных нет.'}</div>`;}
 }catch(_){} });
document.addEventListener('change',e=>{const el=e.target;if(el.id==='review-lot'||el.id==='review-sector')updateTotals();if(el.dataset.filter){filters[el.dataset.filter]=el.value;render();}if(el.dataset.select){el.checked?selected.add(el.dataset.select):selected.delete(el.dataset.select);render();}if(el.dataset.selectAll){const boxes=document.querySelectorAll('[data-select]');boxes.forEach(x=>el.checked?selected.add(x.dataset.select):selected.delete(x.dataset.select));render();}if(el.id==='operation-select'){$('#modal').close();stockDialog(el.value);}});
document.addEventListener('input',e=>{if(e.target.closest('#review-table')||e.target.id==='review-sector')updateTotals();if(e.target.closest('#stock-form'))salePreview();});
document.addEventListener('submit',async e=>{e.preventDefault();const form=e.target,formId=form.getAttribute('id');if(pending)return;const data=Object.fromEntries(new FormData(form));try{
 if(formId==='message-form'){const file=form.querySelector('[name=photo]').files[0];delete data.photo;if(file){if(file.size>10*1024*1024)throw Error('Фото должно быть не больше 10 МБ');data.photo=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Не удалось прочитать фото'));r.readAsDataURL(file)});}const result=await run('message',data,'Сообщение сохранено. Проверьте строки.');if(result){selectedMessage=result.id;tab='inbox';render();}}
 if(formId==='lot-form'){const result=await run('lot',data,'Лот создан. Теперь можно добавить поступление.');if(result){lotDetail=result.id;tab='lots';mode='system';render();}}
 if(formId==='payment-form')await run('payment',data,'Оплата записана. Долг уменьшился.');
 if(formId==='stock-form'){data.ids=[...selected];data.operation=operation;if(operation==='cut'){data.lengths=data.lengths.split(';').map(x=>x.trim());data.seams=data.seams.split(';').map(x=>x.trim());}await run('stock',data,'Операция проведена. Склад и отчёты обновлены.');selected.clear();render();}
 $('#modal').close();
 }catch(err){modalError(err.message);}});
load().catch(e=>{$('#app').innerHTML=`<div class="content"><div class="error">${esc(e.message)}. Обновите страницу после запуска сервера.</div></div>`;});
if(document.modelContext?.registerTool){
 const lifetime=new AbortController();
 const register=tool=>Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});
 register({name:'search_metal_stock',title:'Найти металл на складе',description:'Возвращает текущие свободные и зарезервированные записи по точному диаметру и стенке. Начальные остатки демонстрационные.',inputSchema:{type:'object',properties:{diameter:{type:'number'},wall:{type:'number'}},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},async execute(input){if(!input||typeof input!=='object'||Object.keys(input).some(k=>!['diameter','wall'].includes(k))||Object.values(input).some(v=>typeof v!=='number'||!Number.isFinite(v)||v<=0))throw Error('Передайте положительные числовые diameter и wall');await load();const a=alive().filter(x=>(input.diameter===undefined||x.diameter===input.diameter)&&(input.wall===undefined||x.wall===input.wall));return {count:a.length,tons:sum(a,'tons'),items:a.slice(0,50).map(x=>({diameter:x.diameter,wall:x.wall,length:x.length,seams:x.seams,status:x.status,lot:lot(x.lot_id)?.name}))};}});
 register({name:'open_metal_inbox',title:'Открыть входящие склада',description:'Открывает проверку сообщений без проведения прихода или подтверждения документов.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Параметры не требуются');tab='inbox';render();return {view:'inbox',pending:S.messages.filter(m=>m.status==='draft').length};}});
 window.addEventListener('pagehide',()=>lifetime.abort(),{once:true});
}
window.addEventListener('beforeunload',e=>{if(draftEdits.size){e.preventDefault();e.returnValue='';}});
